{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tune
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tune_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tune/tune_{{ version }}.tar.gz
  sha256: 58fb40cbf74a397e53884b2d49cddc4e3d92b973b48c8e9c0b64181f54497a14

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-gpfit
    - r-cli >=3.3.0
    - r-dials >=1.4.0
    - r-dofuture >=1.0.0
    - r-dplyr >=1.1.0
    - r-foreach
    - r-future >=1.33.0
    - r-generics >=0.1.2
    - r-ggplot2
    - r-glue >=1.6.2
    - r-hardhat >=1.4.1
    - r-lifecycle >=1.0.0
    - r-parsnip >=1.2.0
    - r-purrr >=1.0.0
    - r-recipes >=1.0.4
    - r-rlang >=1.1.0
    - r-rsample >=1.2.1
    - r-tibble >=3.1.0
    - r-tidyr >=1.2.0
    - r-tidyselect >=1.1.2
    - r-vctrs >=0.6.1
    - r-withr
    - r-workflows >=1.2.0
    - r-yardstick >=1.3.0
  run:
    - r-base
    - r-gpfit
    - r-cli >=3.3.0
    - r-dials >=1.4.0
    - r-dofuture >=1.0.0
    - r-dplyr >=1.1.0
    - r-foreach
    - r-future >=1.33.0
    - r-generics >=0.1.2
    - r-ggplot2
    - r-glue >=1.6.2
    - r-hardhat >=1.4.1
    - r-lifecycle >=1.0.0
    - r-parsnip >=1.2.0
    - r-purrr >=1.0.0
    - r-recipes >=1.0.4
    - r-rlang >=1.1.0
    - r-rsample >=1.2.1
    - r-tibble >=3.1.0
    - r-tidyr >=1.2.0
    - r-tidyselect >=1.1.2
    - r-vctrs >=0.6.1
    - r-withr
    - r-workflows >=1.2.0
    - r-yardstick >=1.3.0

test:
  requires:
    - r-testthat
    - r-c50
    - r-censored
    - r-glmnet
    - r-kernlab
    - r-kknn
    - r-modeldata
    - r-randomforest
    - r-scales
    - r-xgboost
  source_files:
    - tests/
  commands:
    - $R -e "library('tune')"                                                                           # [not win]
    - $R -e "testthat::test_dir('tests/testthat/', package='tune', load_package='installed')"           # [not win]
    - "\"%R%\" -e \"library('tune')\""                                                                  # [win]
    - "\"%R%\" -e \"testthat::test_dir('tests/testthat/', package='tune', load_package='installed')\""  # [win]

about:
  home: https://tune.tidymodels.org/
  dev_url: https://github.com/tidymodels/tune
  license: MIT
  summary: The ability to tune models is important. 'tune' contains functions and classes to be used in conjunction with other 'tidymodels' packages for finding reasonable values of hyper-parameters in models, pre-processing methods, and post-processing steps.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
